pipeline {
    
    agent none
    
    environment {
        JFROG_CLI_HOME="/opt/jfrog"
        ARTY_URL='http://192.168.41.41:8081/artifactory'
        ARTY_USER='<CHANGE_ME'
        ARTY_APIKEY='<CHANGE_ME>'
        ARTY_MAIN_REPO="eva-conda"
        ARTY_ID="art6"
    }

    parameters {
        string(name: 'promotion_repo', defaultValue: 'eva-conda-int-local', description: 'target repo for promotion')
        booleanParam(name: 'scan_build', defaultValue: false, description: 'Xray scan')
        string(name: 'agent', defaultValue: 'linux', description: 'Jenkins agent name')
    }
    
    stages {
        
        stage("Config env") {
           agent { label params.agent }
           steps {
                git credentialsId: 'cyan21', branch: 'master', url: 'https://github.com/cyan21/conda-pipeline.git'
                
                sh "cp CI/JenkinsBuild/Dockerfile . " 
           }
        }

        stage("Build package") {
           agent { label params.agent dockerfile {
                   additionalBuildArgs  "--build-arg ARTY_URL=${env.ARTY_URL} --build-arg ARTY_USER=${env.ARTY_USER} --build-arg ARTY_APIKEY=${env.ARTY_APIKEY} --build-arg ARTY_ID=${env.ARTY_ID}" 
               }
           }
           steps {
                sh '''
                    jfrog --version
                    conda info
                    scripts/init.sh -c /opt/jfrog -u $ARTY_USER -k $ARTY_APIKEY -l $ARTY_URL -r $ARTY_MAIN_REPO
                    scripts/build.sh -i $JOB_NAME -n $BUILD_NUMBER -c /opt/conda/pkgs -r $ARTY_MAIN_REPO -a $ARTY_ID
                '''
            }
        }

        stage('Promote Build Info') {
           agent { label params.agent dockerfile {
                   additionalBuildArgs  "--build-arg ARTY_URL=${env.ARTY_URL} --build-arg ARTY_USER=${env.ARTY_USER} --build-arg ARTY_APIKEY=${env.ARTY_APIKEY} --build-arg ARTY_ID=${env.ARTY_ID}" 
               }
           }
            steps {
                echo "Performing promotion ..."
                
                sh "jfrog rt bpr --status='Integration' --comment='passed non regression tests' $JOB_NAME $BUILD_ID ${params.promotion_repo}"
            }    
        }

    } // end stages
}         

